/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : freemaster_cfg.H
**     Project   : Test
**     Processor : 56F8323
**     Version   : Component 01.006, Driver 01.03, CPU db: 2.87.081
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 17.10.2012, 17:58
**     Abstract  :
**          FreeMASTER Serial Communication Driver configuration file
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __FREEMASTER_CFG_H
#define __FREEMASTER_CFG_H

/* Select interrupt or poll-driven serial communication */
#define FMSTR_LONG_INTR         0
#define FMSTR_SHORT_INTR        0
#define FMSTR_POLL_DRIVEN       1      /* No interrupt needed, polling only */

/* SCI communication */
#define FMSTR_USE_SCI           1      /* Use SCI interface */
#define FMSTR_SCI_BASE          62080  /* SCI Base address is same as SCI Baud Rate register address */
#define FMSTR_USE_JTAG          0      /* Disable JTAG interface */

/* FreeMaster communication buffer */
#define FMSTR_COMM_BUFFER_SIZE  64     /* Input/output communication buffer size */
#if FMSTR_SHORT_INTR
#define FMSTR_COMM_RQUEUE_SIZE  32     /* Receive FIFO queue size (use with FMSTR_SHORT_INTR only) */
#endif

/* Application command support */
#define FMSTR_USE_APPCMD        0      /* Application commands support disabled */

/* Oscilloscope support */
#define FMSTR_USE_SCOPE         1      /* Scope enabled */
#define FMSTR_MAX_SCOPE_VARS    8      /* Max. number of scope variables (2..8) */

/* Recorder support */
#define FMSTR_USE_RECORDER      1      /* Recorder support enabled */
#define FMSTR_REC_BUFF_SIZE     4096   /* Recorder buffer size */
#define FMSTR_USE_FASTREC       0      /* Fast recorder support disabled */
#define FMSTR_REC_OWNBUFF       0      /* User-allocated rec. buffer is not used */
#define FMSTR_REC_FARBUFF       0      /* Buffer is not putted in "fardata" section */
#define FMSTR_MAX_REC_VARS      8      /* Max. number of recorder variables (2..8) */
#define FMSTR_REC_TIMEBASE      (32768+31)  /* Recorder timebase */
#define FMSTR_USE_BRIEFINFO     0      /* Full board information structure is required becouse recorder is used */

/* Target-side addressing support */
#define FMSTR_USE_TSA           0      /* Disable TSA functionality */

#define FMSTR_USE_READMEM       1      /* Enable read memory commands */
#define FMSTR_USE_WRITEMEM      1      /* Enable write memory commands */
#define FMSTR_USE_WRITEMEMMASK  1      /* Enable masked write memory commands */

//#define FMSTR_USE_READVAR       0      /* Disable read variable fast commands */
#define FMSTR_USE_READVAR       1      /* Disable read variable fast commands */
#define FMSTR_USE_WRITEVAR      0      /* Disable write variable fast commands */
#define FMSTR_USE_WRITEVARMASK  0      /* Disable write variable bits fast commands */

/* SFIO support */
#define FMSTR_USE_SFIO          0      /* SFIO support disabled */

#endif                                 /* __FREEMASTER_CFG_H */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/

